### ISSUE TITLE
PHP CakePHP

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-guides#15]
Need a guide for CakePHP

**Comment by sdomino** [comment]
- [x] Update content in `articles/php/cakephp/add-a-database.md`
- [x] Update content in `articles/php/cakephp/configure-yii.md`
- [x] Update content in `articles/php/cakephp/existing-app.md`
- [x] Update content in `articles/php/cakephp/from-scratch.md`

**Comment by sanderson** [comment]
Thanks for updating all of these @narendravaghela!
