### ISSUE TITLE
Moleculer guides

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-guides#76]
https://moleculer.services/

**Comment by davidroman0O** [comment]
Pretty simple setup : 

`moleculer init project-simple name-project`
Then copy/paste the `config/nginx.conf` file from the nodejs template of Nanobox
Then add a Redis component in the `boxfile.yml`
Add those lines in the `molecular.config.js` file : 

- ``` transporter: `redis://${process.env.DATA_REDIS_HOST}:6379`, ```
- ```cacher: `redis://${process.env.DATA_REDIS_HOST}:6379`, ```

Then run `nano box run npm start`

I hope I didn't forget anything ! :D

**Comment by sanderson** [comment]
@davidroman0O I just pushed Moleculer guides to the `new/moleculer` branch. Do you want to take a look?

https://github.com/nanobox-io/nanobox-guides/tree/new/molecular
